### ISSUE TITLE
Who can create a Game?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#12]
Is this an admin feature? Can users make games? Can they submit a Game Request?

**Comment by AccaliaDeElementia** [comment]
Hmm... Tough question.

Admins certainly can, but regular users maybe can't?

perhaps some sort of groups based permission thing?

**Comment by Kaelas17** [comment]
I would say admins create games, yeah. Create a system open to any user to submit requests to admins to create a game and promote the requestor to GMin for that game.

 I'd also suggest the requests enter a shared pool where all admins can see and act- this prevents backlogs forming as would be the case if there's a designated 'game creator' admin that's afk for too long. And by having it a shared pool, instead of just allowing all admins to do it, it (helps) prevent a user from just spamming all the admins until someone approves an offensive game idea- basically, just keeps them all on the same page.

**Comment by RaceProUK** [comment]
A game approvals queue sounds like a good idea, though maybe there can be an admin-level option to disable it, for if there's a very active board one day. But that's something we can add later :smile:

**Comment by yamikuronue** [comment]
Okay, it seems we're agreed :)
