### ISSUE TITLE
How do we handle deletion?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#14]
Do we want soft-deletes? Hard deletes? Sometimes one and sometimes the other? Is the answer the same for all entities? What about self-deletes vs admin deletes?

Things I can think of that might be able to be deleted:
 - Threads/scenes
 - Games/boards
 - Users

**Comment by AccaliaDeElementia** [comment]
Users should probably be inactivated rather than deleted if they're active in a game.

Not that i anticipate that being a thing.

We will have to figure out how to handle spam.

the other two categories.... that's harder.

**Comment by Kaelas17** [comment]
I would, at the least, have a means of hard deleting game/threads available to admins in case someone crosses a (legal) line. 

@AccaliaDeElementia agreed with being inactive rather than deleting users in an active game, particularly if deleting a user deletes their posts or some such.That could cause all sorts of havoc

For threads/games, I would have it so the OP and GM can soft-delete but only admins can hard-delete. Just in case someone decides to flip a table and deletes a game as petty revenge, the admins can restore the game for the other users.

I'm assuming that users deleting their own, singular, posts is a given?

(I'm assuming hard deletes is a total wipe and soft is deleting it but storing a copy where regular users can't see it, yeah?)

**Comment by yamikuronue** [comment]
I can confirm your terminology is correct: a soft delete can be undone, but a hard delete cannot.

**Comment by RaceProUK** [comment]
Hard deletes are a royal PITA to handle correctly when it comes to data integrity; for my part, I'd want to ensure the DB has all its foreign keys set up as constraints, and disable cascading deletes. So I think we should try to minimise the situations in which hard deletion is possible, and for the few parts where it _is_ possible, provide them only to admins, with a big warning that the operation is irreversible. And it should only be allowed for data that has already been soft-deleted, but then I'm willing to admit that last bit is a style thing more than a genuine concern :smile:

**Comment by AccaliaDeElementia** [comment]
so, I think we're all in agreement here on soft deletes, if a need to purge deleted data comes up we'll discuss changing things at that point.

* Users will be inactivated and their usernames released (changed to something like `anonymous_000001`)
* posts will be marked deleted and hidden from the UI, Admins might be able to still see them, we'll discuss that as part of UI discussions
* Topics/boards will behave similarly to posts

no hard deletes will be available through the software at this time. as i said we'll discuss the need to purge deleted data when the need arises.

**Comment by RaceProUK** [comment]
This can be enforced at the DB layer; all I need to do is turn on Sequelize's Paranoid mode. Then we just use the normal `delete` operations; the data will remain in the DB, marked as Deleted.
