### ISSUE TITLE
Document the database design

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#18]
Let's nail down the basic database design in advance :)

**Comment by RaceProUK** [comment]
With any luck, this is the link to the design:
https://drive.google.com/file/d/0BwWJ1JEDb58dRXk2ekRTUG04NlU/view?pli=1

**Comment by AccaliaDeElementia** [comment]
that's the document, but google drive seems to not want to open it in draw.io like it should....

hmm....

**Comment by AccaliaDeElementia** [comment]
ah. there we go. yeah that looks sensible to start with. still a bit barren with the data fields, but we're just planning entities and relationships at this time so that's okay.

Looks good to me.

**Comment by RaceProUK** [comment]
That's the intention; get the entities and relationships sorted, _then_ worry about the actual data :smile:

**Comment by yamikuronue** [comment]
Yeah, we're doing somewhat agileish, I just wanted to get the overall schematic laid out so we have some foundation to build on :)

**Comment by RaceProUK** [comment]
The design as it currently stands should cover most of what we want to store; however, I'd like to reach an agreement on how to handle notifications and private messages before signing off on the design. I don't see either making for anything complex, but it'd be good to get something down sooner rather than later.

**Comment by yamikuronue** [comment]
I feel like we could decide those later, when we start working on those stories, right?

**Comment by RaceProUK** [comment]
Hmm... come to think of it, every possible solution I can come up with wouldn't require anything already defined to be changed; it'd be some new fields and tables, and that's easy to do.

So that means this WI is about the _core_ schema; notifications and PMs can be extensions to that. If we're happy with the structure and the relationships, then I'd like to get started on fleshing out the table definitions with the fields we'll need :smile:

**Comment by yamikuronue** [comment]
Sounds great :) I think we can actually close this; after all, you'll probably snag the tickets for creating the database structures for the various stories as we go and keep the document up to date, right?

**Comment by RaceProUK** [comment]
~~My evil plot has been discovered!~~ In all likelihood, yes :angel:

**Comment by yamikuronue** [comment]
+1
