### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by RaceProUK** [SockDrawer/SockRPG#23]
We know we want an e-mail system in place to send alerts when plays are made, but do we want to have an on-site system too? Maybe with browser alerts? There's also the question of whether we persist notifications or not.

**Comment by Kaelas17** [comment]
Hmmm. By browser alerts, do you mean how google used to have a discrete pop-up when someone gchated you? Because I rather liked that feature- it's more obvious than just an email and if I still have the forum tab open, I'm almost certainly interested in replying/reading quickly.  

In regards to the email alert, i would love a feature that would allow how often they go out- bonus points if they can be tweaked by thread or at least tag (if we go with tagging threads).  While I might want to be alerted for each and every post in a game I'm playing, I'd likely prefer a more relaxed frequency (daily probably) for games I'm just watching or OC threads I'm not a GM for.

**Comment by RaceProUK** [comment]
I was thinking like the ones on ServerCooties.com, which I guess are the same thing :smile:

**Comment by Kaelas17** [comment]
Does anyone have any questions, comments or concerns about this or did I actually says something so perfect that it pleases all the people? 'cause I'll be all smug and everything if I did but I kinda doubt it.

**Comment by AccaliaDeElementia** [comment]
I'm going with:

Email notifications/digests: Yes, but not for alpha. let's get the boards working and add this when we hit beta.
Browser notifications: Yes, but for late alpha. Let's get the basic boards working and add this when we start to make with the pretty.
