### ISSUE TITLE
Task: Database structure: Users

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#38]
Implement the database persistance for users.

Required for #3 and #4

**Comment by RaceProUK** [comment]
Mandatory fields:
- ID
- Username

Since we're using OpenID and not storing passwords, there won't be a password field. However, we may need some sort of OpenID token field; need to look into that.

Now, the fields outlined so far are the minimum for a functional system; however, we all know forums store a lot more info on users than their ID, name, and creds. So, what else do we want to store? Obviously we don't need to think of everything now, but it'll be good to have a few fields aside from the minimum required. For testing purposes, if nothing else.
